### ISSUE TITLE
The error "an illegal memory access " happens when I set gpu_id >=1

### ISSUE THREAD

**Issue by ShawnshanksGui** [shacklettbp/gpu_hideseek#4]
Hi,
  I have 4 A6000 cards in a server, I set gpu_id >=1, and the error is as follows:
  Error at /home/guifei/projects/madrona/test/gpu_hideseek/external/madrona/src/mw/cuda_exec.cpp:1404 in madrona::GPUEngineState madrona::initEngineAndUserState(uint32_t, uint32_t, uint32_t, void *, uint32_t, void *, uint32_t, uint32_t, const madrona::GPUKernels &, madrona::ExecutorMode, cudaStream_t)
an illegal memory access was encountered
Aborted (core dumped)

thx

**Comment by shacklettbp** [comment]
This should now be fixed. Make sure you pull and also update submodules as it required a change in the Madrona repo. I'll push a fix to the escape room repo as well shortly. Thanks for the report!

**Comment by ShawnshanksGui** [comment]
thx

**Comment by ShawnshanksGui** [comment]
Hi,
"The gpu_id can be set to 1 or higher in the 'hideseek' and 'escape room' repos, but not in others."

**Comment by shacklettbp** [comment]
Do you mean madrona_simple_example?

**Comment by ShawnshanksGui** [comment]
yes

**Comment by shacklettbp** [comment]
The madrona submodule just needs to be updated on that repo. Is there a specific repo where this is blocking your work?

**Comment by ShawnshanksGui** [comment]
I recloned and rebuilt madrona_simple_example from scratch, it seems no block. But it does not work.

**Comment by shacklettbp** [comment]
Yeah, madrona_simple_example *has not* been updated. But I'm wondering why that matters? madrona_simple_example doesn't have any functionality in it. If you have a fork created off of madrona_simple_example, you can update the madrona submodule to madrona latest main *in your fork* independently of the status of madrona_simple_example.

**Comment by ShawnshanksGui** [comment]
thx，I will have a try
