### ISSUE TITLE
Rewards and visibility masks not working as expected.

### ISSUE THREAD

**Issue by zelaix** [shacklettbp/gpu_hideseek#5]
Hi, I'm trying to train RL agents in this environment, but I find the agents can't see the entities in front of them and the reward is not right.

For example, when agent[i] (hider) is in front of agent[j] (seeker), `sim.visible_agents_mask_tensor().to_torch[i, j, 0]` should be 1 and `sim.reward_tensor().to_torch()[j, 0]` should be 1. However, I found the mask to be 0 and reward to be -1.

To stably reproduce the result, I changed `generateTrainingEnvironment` in src/level_gen.cpp to fix the initial position and rotation of hider[0], seeker[0], and seeker[1] and ensure that seeker[0] and seeker[1] can see hider[0]. The change is as follows.
```C++
// change line 253-258: fix hider pos and rot
Vector3 pos {0.f, 4.f, 0.f};
if (i == 1) {
    pos = Vector3 {-100.f, 0.f, 0.f};
} else if (i == 2) {
    pos = Vector3 {100.f, 0.f, 0.f};
}

const auto rot = Quat::angleAxis(0 * math::pi, {0, 0, 1});
```

```C++
// change line 275-292
if (i == 0) {
    Vector3 pos {0.f, 0.f, 0.f};
    const auto rot = Quat::angleAxis(0 * math::pi, {0, 0, 1});
    Diag3x3 scale = {1.0f, 1.0f, 1.0f};

    AABB aabb = obj_mgr.rigidBodyAABBs[4];
    aabb = aabb.applyTRS(pos, rot, scale);

    if (checkOverlap(aabb) || rejections == max_rejections) {
        makeDynAgent(pos, rot, false, num_hiders + i);
        break;
    }

    rejections++;
} else {
    Vector3 pos {0.f, 8.f, 0.f};
    const auto rot = Quat::angleAxis(1 * math::pi, {0, 0, 1});
    Diag3x3 scale = {1.0f, 1.0f, 1.0f};

    AABB aabb = obj_mgr.rigidBodyAABBs[4];
    aabb = aabb.applyTRS(pos, rot, scale);

    if (checkOverlap(aabb) || rejections == max_rejections) {
        makeDynAgent(pos, rot, false, num_hiders + i);
        break;
    }

    rejections++;
}
```
Then I initiated an environment, set actions of all agents to be [5, 5, 5, 0, 0], and ran sim.step() for 240 times, but the`visible_agents_mask_tensor` and `reward_tensor` are not right for any step.

I think the problem might be the `checkVibility` function in src/sim.cpp is not working properly. The entity returned by `bvh.traceRay` is not right. Could you please check this problem?

**Comment by shacklettbp** [comment]
Thanks for the bug report. I will look into this is more detail tomorrow. How many worlds? 1?

**Comment by zelaix** [comment]
Yes, 1 world.

**Comment by shacklettbp** [comment]
Just confirming that I've reproduced this! Looks like there's a been a big regression somewhere.

**Comment by shacklettbp** [comment]
This should now be fixed. Embarrassingly, I broke this while trying to make the agents cuter, which modified their center position and caused rays to be launched into the ground. Please let me know if the latest commit fixes the problem for you!

Also, let me know how your experiments training agents in this environment go!

**Comment by zelaix** [comment]
Thanks! The problem is fixed. I'll share the results once the training is done.
